# !!!NOTE!!!
# A plugin for allure needs to be installed on the azure instance - https://marketplace.visualstudio.com/items?itemName=qameta.allure-azure-pipelines
# For more info, please visit - https://allurereport.org/docs/integrations-azure/
parameters:
- name: testTags
  displayName: "Test tag to be run"
  type: string
  default: "@test"
- name: browsers
  displayName: "Browsers - separated by space"
  type: string
  default: "chromium"
- name: parallelization_number
  displayName: "Parallelization"
  type: number
  default: 2
  values:
  - 1
  - 2
  - 3
  - 4
  - 5

trigger:
  - main

pool:
  vmImage: ubuntu-latest


steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "18"
    displayName: "Install Node.js"
  - script: npm ci
    displayName: "npm ci"
  - bash: |
      scriptBuilder="npx playwright test";
      for i in ${{ parameters.browsers }}; do
        scriptBuilder+=" --project ${i}"; # Set projects in loop
      done
      scriptBuilder+=" --grep ${{ parameters.testTags }}" # Set tags
      scriptBuilder+=" --workers ${{ parameters.parallelization_number }}" # Set parallelization

      echo "my var $scriptBuilder";
      echo "##vso[task.setvariable variable=test_run_script;]$scriptBuilder";
    displayName: "Prepare runnable script"
  - script: npx playwright install --with-deps
    displayName: "Install Playwright"
  - script: $(test_run_script)
    displayName: "Run Playwright tests"
    env:
      CI: "true"
    condition: succeededOrFailed()
  - task: PublishAllureReport@1
    displayName: "publish allure report"
    inputs:
      testResultsDir: "allure-results"
      reportName: "Test Report"
    condition: succeededOrFailed()
