version: '3.8'
services:
    playwright-test:
        image: playwright-test
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./allure-results/:/app/allure-results
            - ./logs/:/app/logs
